# Auto-generated by IDE. Changes by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/BeRail.cpp) \
                 $$quote($$BASEDIR/src/Models/Connection.cpp) \
                 $$quote($$BASEDIR/src/Models/Disruption.cpp) \
                 $$quote($$BASEDIR/src/Models/Station.cpp) \
                 $$quote($$BASEDIR/src/Models/ViaStation.cpp) \
                 $$quote($$BASEDIR/src/Services/ConnectionService.cpp) \
                 $$quote($$BASEDIR/src/Services/DisruptionService.cpp) \
                 $$quote($$BASEDIR/src/Services/FavoriteService.cpp) \
                 $$quote($$BASEDIR/src/Services/StationService.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/DisruptionsViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/FavoritesViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/RouteViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/StationViewModel.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/BeRail.hpp) \
                 $$quote($$BASEDIR/src/Models/Connection.hpp) \
                 $$quote($$BASEDIR/src/Models/Disruption.hpp) \
                 $$quote($$BASEDIR/src/Models/Station.hpp) \
                 $$quote($$BASEDIR/src/Models/ViaStation.hpp) \
                 $$quote($$BASEDIR/src/Services/ConnectionService.hpp) \
                 $$quote($$BASEDIR/src/Services/DisruptionService.hpp) \
                 $$quote($$BASEDIR/src/Services/FavoriteService.hpp) \
                 $$quote($$BASEDIR/src/Services/StationService.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/DisruptionsViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/FavoritesViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/RouteViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/StationViewModel.hpp)

    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/BeRail.cpp) \
                 $$quote($$BASEDIR/src/Models/Connection.cpp) \
                 $$quote($$BASEDIR/src/Models/Disruption.cpp) \
                 $$quote($$BASEDIR/src/Models/Station.cpp) \
                 $$quote($$BASEDIR/src/Models/ViaStation.cpp) \
                 $$quote($$BASEDIR/src/Services/ConnectionService.cpp) \
                 $$quote($$BASEDIR/src/Services/DisruptionService.cpp) \
                 $$quote($$BASEDIR/src/Services/FavoriteService.cpp) \
                 $$quote($$BASEDIR/src/Services/StationService.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/DisruptionsViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/FavoritesViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/RouteViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/StationViewModel.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/BeRail.hpp) \
                 $$quote($$BASEDIR/src/Models/Connection.hpp) \
                 $$quote($$BASEDIR/src/Models/Disruption.hpp) \
                 $$quote($$BASEDIR/src/Models/Station.hpp) \
                 $$quote($$BASEDIR/src/Models/ViaStation.hpp) \
                 $$quote($$BASEDIR/src/Services/ConnectionService.hpp) \
                 $$quote($$BASEDIR/src/Services/DisruptionService.hpp) \
                 $$quote($$BASEDIR/src/Services/FavoriteService.hpp) \
                 $$quote($$BASEDIR/src/Services/StationService.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/DisruptionsViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/FavoritesViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/RouteViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/StationViewModel.hpp)

    }

}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/BeRail.cpp) \
                 $$quote($$BASEDIR/src/Models/Connection.cpp) \
                 $$quote($$BASEDIR/src/Models/Disruption.cpp) \
                 $$quote($$BASEDIR/src/Models/Station.cpp) \
                 $$quote($$BASEDIR/src/Models/ViaStation.cpp) \
                 $$quote($$BASEDIR/src/Services/ConnectionService.cpp) \
                 $$quote($$BASEDIR/src/Services/DisruptionService.cpp) \
                 $$quote($$BASEDIR/src/Services/FavoriteService.cpp) \
                 $$quote($$BASEDIR/src/Services/StationService.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/DisruptionsViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/FavoritesViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/RouteViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/StationViewModel.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/BeRail.hpp) \
                 $$quote($$BASEDIR/src/Models/Connection.hpp) \
                 $$quote($$BASEDIR/src/Models/Disruption.hpp) \
                 $$quote($$BASEDIR/src/Models/Station.hpp) \
                 $$quote($$BASEDIR/src/Models/ViaStation.hpp) \
                 $$quote($$BASEDIR/src/Services/ConnectionService.hpp) \
                 $$quote($$BASEDIR/src/Services/DisruptionService.hpp) \
                 $$quote($$BASEDIR/src/Services/FavoriteService.hpp) \
                 $$quote($$BASEDIR/src/Services/StationService.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/DisruptionsViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/FavoritesViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/RouteViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/StationViewModel.hpp)

    }

}

INCLUDEPATH +=  $$quote($$BASEDIR/src/Models) \
         $$quote($$BASEDIR/src/ViewModels) \
         $$quote($$BASEDIR/src/Services) \
         $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../assets/*.qml)

}

TRANSLATIONS =  $$quote($${TARGET}_de.ts) \
         $$quote($${TARGET}_en.ts) \
         $$quote($${TARGET}_fr.ts) \
         $$quote($${TARGET}_nl.ts) \
         $$quote($${TARGET}.ts)

